### ISSUE TITLE
No module named 'torch'

### ISSUE THREAD

**Issue by XComhghall** [enfein/xijinping-tts#4]
```
Traceback (most recent call last):
  File "/xijinping-tts/app.py", line 14, in <module>
    import streamlit as st
ModuleNotFoundError: No module named 'streamlit'
```
我是完全的电脑小白。我猜运行这个程式，就是运行 app.py？
运行 app.py 之后，就有了如上的 error 提示。删掉 `.streamlit` 文件夹的 `.` 就好了，不过又有
```
Traceback (most recent call last):
  File "/xijinping-tts/app.py", line 15, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```
感谢您的工作与付出！

**Comment by enfein** [comment]
这个项目有好几个外部代码库的依赖。最简单的方法是使用 docker 容器把所有的依赖一起打包。指令参照 https://github.com/enfein/xijinping-tts/blob/main/README.md 即可。

如果你不使用容器，也可以参照 https://github.com/enfein/xijinping-tts/blob/main/Dockerfile 手动运行里面的指令。不过我不建议小白这么做，因为会遇到很多问题。

**Comment by XComhghall** [comment]
嗷嗷 谢谢！
依次使用 README.md 的那两行代码吗？<tag> 是要替换什么码进去，还是指令就按原样就好？
打包之后可以卸载 Docker 吗？我好像别的没有用到 Docker 的地方

**Comment by enfein** [comment]
我上传了一个编译好的容器，可以直接下载运行。详情见项目主页。
